name: Keep Supabase Active

on:
  schedule:
    - cron: '0 0 * * 1' # 毎週月曜日の0:00に実行
  workflow_dispatch: # 手動トリガーを追加

jobs:
  send-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Supabase
        run: |
          curl -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          "https://osaenrgwaxuhdsevcnac.supabase.co/rest/v1/employees?select=*"


